# Generated by Django 5.2.5 on 2025-08-29 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='olcha.category'),
        ),
    ]
